import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import os from 'os';

export const metadata: Metadata = {
  title: {
    template: "MOCA | %s",
    default: "MOCA"
  },
  description: "Generated by create next app",
};

export async function getSession() {
  const cookieStore = cookies()
  const allCookies = cookieStore.getAll()
  const host = os.hostname()
  
  // 쿠키를 헤더 형식으로 변환
  const cookieHeader = allCookies
    .map(cookie => `${cookie.name}=${cookie.value}`)
    .join('; ')


  const res = await fetch(`http://${host}:8000/session-chk`, {
    method: "GET",
    credentials: "include",  // 중요!
    headers: {
      'Accept': 'application/json',
      Cookie: cookieHeader
    }
  });

  const data = await res.json();

  return data
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <div className="content">
        {children}
      </div>
      <div className="footer"></div>
      </body>
    </html>
  );
}
